apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent5
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkinst-yamltest
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.9.2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: jenkins-master
      app.kubernetes.io/instance: jenkinst-yamltest
  template:
    metadata:
      labels:
        app.kubernetes.io/component: jenkins-master
        app.kubernetes.io/instance: jenkinst-yamltest
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-1.9.2
    spec:
      containers:
      - name: jenkins-agent5
        image: jenkins/jnlp-slave
        env:
        # Define the environment variable
        - name: JENKINS_TUNNEL
          value: jenkinst-yamltest-agent:50000
        - name: JENKINS_AGENT_NAME
          value: jenkins-agent5
        - name: JENKINS_URL
          value: http://10.1.175.172/test3514
        - name: JENKINS_SECRET
